name: Excel Design
address1: 321 North Mall Drive, Suite J-101
address2: St. George, UT 84790
phone: 435-619-4586
email: charles@exceldesign.us
fax: 435.608.4586
lat: '37.1003124'
lng: '-113.5727883'
mapzoom: 13
version: 3.0.3
permalink: pretty
excerpt_separator: ///
collections:
  main-pages:
    output: true
  testimonials:
    hide_content: true
  faqs: