name: Your Website Name
version: 3.0.3
permalink: pretty
excerpt_separator: ///
collections:
  main-pages:
    output: true
  makes:
    output: true
  models:
    output: true
  trucks:
    output: true